name: ci-golang-workflow
on:
  pull_request:
    branches:
      - develop

jobs:
  check-application:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.21", "1.21.3"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          # go-version: 1.21.3
          go-version: ${{ matrix.go }}
      - run: cd src && go test
      - run: cd src && go run math.go

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./src
          push: true # não fazer o push no dockerhub
          tags: jonasborgeslm/teste-git:latest
